//
//  SoCMViewController.m
//  HelloWorld4iPhone
//
//  Created by Nicholas Outram on 27/09/2011.
//  Copyright (c) 2011 University of Plymouth. All rights reserved.
//

//This is the implmentation file of our controller

#import "SoCMViewController.h"

@implementation SoCMViewController {
    //Note that iVar declarations now go here (if you want to be purist ;o)
    //IBOutlet is defined as nothing - but it's important as it flaggs to Interface Builder that this is a pointer to an object archived in a nib file.
    IBOutlet UILabel *messageLabel;
}

// Most of the code below is generated by the template. Most of it is useful
// These methods override implementations in the baseclass (UIViewController) 

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Release any cached data, images, etc that aren't in use.
}

#pragma mark - View lifecycle

- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.
}

- (void)viewDidUnload
{
    [super viewDidUnload];
    // Release any retained subviews of the main view.
    // e.g. self.myOutlet = nil;
}

- (void)viewWillAppear:(BOOL)animated
{
    [super viewWillAppear:animated];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
}

- (void)viewWillDisappear:(BOOL)animated
{
	[super viewWillDisappear:animated];
}

- (void)viewDidDisappear:(BOOL)animated
{
	[super viewDidDisappear:animated];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    // Return YES for supported orientations
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}

// Actions

-(IBAction)doButtonTouched:(id)sender
{
    //Log a message to the console
    NSLog(@"Hello World");
    
    //Set the "text" property of the label to @"Hello World"
    [messageLabel setText:@"Hello World"];
}
@end
